name: 'Push Laravel I18n Files'
description: 'Finds and parses Laravel localization files and push its content to Localang.'
inputs:
  api-key:
    description: 'API Key to update translations on localang.xyz'
    required: true
  project-id:
    description: 'ID of project on localang.xyz'
    required: true
  folder:
    description: 'Folder with translations'
    required: false
    default: 'lang'

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Create Local Script
      run: curl https://localang.xyz/laravel-i18n-push-script -o localang-i18n-laravel-push-action.php
      shell: bash
    - name: Run Pull Script
      run: php -f localang-i18n-laravel-push-action.php ${{ inputs.api-key }} ${{ inputs.project-id }} ${{ inputs.folder }}
      shell: bash
    - name: Delete Local Script
      run: rm localang-i18n-laravel-push-action.php
      shell: bash
